# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(748, 331)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 721, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.roll = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.roll.setObjectName("roll")
        self.gridLayout.addWidget(self.roll, 0, 1, 1, 1)
        self.rollTotal = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.rollTotal.setReadOnly(True)
        self.rollTotal.setObjectName("rollTotal")
        self.gridLayout.addWidget(self.rollTotal, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight: bold")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.rollCount = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollCount.sizePolicy().hasHeightForWidth())
        self.rollCount.setSizePolicy(sizePolicy)
        self.rollCount.setObjectName("rollCount")
        self.gridLayout.addWidget(self.rollCount, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setStyleSheet("font-weight: bold")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.nut = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nut.setObjectName("nut")
        self.gridLayout.addWidget(self.nut, 1, 1, 1, 1)
        self.nutWeight = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nutWeight.sizePolicy().hasHeightForWidth())
        self.nutWeight.setSizePolicy(sizePolicy)
        self.nutWeight.setObjectName("nutWeight")
        self.gridLayout.addWidget(self.nutWeight, 1, 2, 1, 1)
        self.nutTotal = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nutTotal.setReadOnly(True)
        self.nutTotal.setObjectName("nutTotal")
        self.gridLayout.addWidget(self.nutTotal, 1, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.roll.setPlaceholderText(_translate("Dialog", "Cena za sztuke"))
        self.label.setText(_translate("Dialog", "Bułka"))
        self.label_2.setText(_translate("Dialog", "Orzechy"))
        self.nut.setPlaceholderText(_translate("Dialog", "Cena za kilogram"))
